## Numpy and Pandas

In [1]:
# Numpy stands for numerical python
# It is a package used for  multi dimensional arrays

In [3]:
import numpy as np
# if there is an error you will have to type 'pip install numpy' into anaconda prompt

In [3]:
# Difference between a numpy array and a  list?
# 1) size
# 2) speed
# 3) functionality
# 4) relied upon

In [4]:
np.

# How many functions are there?


# Answer: a lot

SyntaxError: invalid syntax (<ipython-input-4-6c7255bdc648>, line 1)

In [4]:
# to create a basic array
array_variable = np.array({[5, 8, 67, 67, 3]})
array_variable

array([1, 2, 3, 4, 6])

In [7]:
# you are pretty much putting it in a list
list_ = [5, 8, 67, 67,3]

array_variable = np.array(list_)

array_variable

array([ 5,  8, 67, 67,  3])

In [8]:
type(array_variable)

numpy.ndarray

In [9]:
# array_variable.TAB

#there are many functions built on

array_variable.

SyntaxError: invalid syntax (<ipython-input-9-d0c97258bd10>, line 5)

In [10]:
# you can sort of build matrices with lists i.e.

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# however this is rusty i.e.
my_matrix.extend([10])
my_matrix
#what is this now? I's no longer a matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], 10]

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

In [13]:
np.arange(0,10)   # like range, except it builds numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [204]:
np.arange(0,21,4)

array([ 0,  4,  8, 12, 16, 20])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5,5,5)) # a 5 by 5 by 5 by 5 dimension space of zeros

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [6]:
np.((3,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [18]:
np.eye(6)  # identity matrix multiplied by this any matrix will return itself

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [206]:
np.linspace(1,100,21) # returns 21 evenly spaced numbers betwwen 1 and 100

array([  1.  ,   5.95,  10.9 ,  15.85,  20.8 ,  25.75,  30.7 ,  35.65,
        40.6 ,  45.55,  50.5 ,  55.45,  60.4 ,  65.35,  70.3 ,  75.25,
        80.2 ,  85.15,  90.1 ,  95.05, 100.  ])

# Built in Random Function

In [20]:
np.random.rand(10)  # 10 random numbers between 0 and 1

array([0.31618707, 0.40984599, 0.85502777, 0.95216556, 0.86836781,
       0.36513761, 0.50534528, 0.86844859, 0.98757104, 0.92841808])

In [21]:
np.random.rand(5,5,2) # 50 random numbers between 0 and 1 arranged in a 5x5x2

array([[[0.53793937, 0.06643378],
        [0.67481711, 0.50129332],
        [0.63427007, 0.61907613],
        [0.16772099, 0.37087938],
        [0.42164151, 0.06447209]],

       [[0.76677345, 0.7801443 ],
        [0.52881468, 0.28692784],
        [0.44995435, 0.03381204],
        [0.02453887, 0.35884635],
        [0.75346296, 0.60074087]],

       [[0.30329159, 0.99931868],
        [0.60235398, 0.5863623 ],
        [0.08577163, 0.47727657],
        [0.57876216, 0.16776232],
        [0.9904322 , 0.85988763]],

       [[0.23525962, 0.17023852],
        [0.92753577, 0.57377734],
        [0.81953288, 0.69315076],
        [0.14994004, 0.36718555],
        [0.78646953, 0.78148085]],

       [[0.14244523, 0.8454325 ],
        [0.39534472, 0.77865495],
        [0.83456865, 0.38599044],
        [0.82623871, 0.66043694],
        [0.92976438, 0.61368021]]])

In [23]:
np.random.randn(3,3,3) # normal distribution

array([[[-0.99140473, -0.74954581, -1.66314165],
        [-0.82955496, -1.23548989,  2.33387868],
        [ 0.07151376,  0.92584257, -0.65434485]],

       [[-0.83726597, -1.46390205,  1.92444701],
        [-1.05909131, -2.03226362, -0.69114149],
        [ 0.86669818, -0.62049276,  1.13161548]],

       [[ 0.34395976, -0.50416036, -1.83757229],
        [ 1.29417093, -0.19764854, -0.56098726],
        [-1.0864881 ,  0.17741435, -0.03180155]]])

In [207]:
np.random.randint(0,100,22) # 22 numbers randomly distributed between 0 and 100

array([54, 80, 47, 82, 41, 51, 33, 43, 98, 42,  1, 91,  0, 13, 35, 24, 24,
        0, 66, 66, 72, 33])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [7]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([30, 11, 24, 11,  0, 24, 35, 11, 35, 15])

## Reshape
Returns an array containing the same data with a new shape.

In [28]:
arr.reshape(5,5) # changes arr from 1 dimension to 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr   # remember that some fuctions are inplace some arent
# i.e. reshape changed arr, but did not save

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
ranarr

array([27,  3, 46, 24, 29,  5, 48, 19, 46, 24])

In [10]:
ranarr.argmax()

6

In [32]:
ranarr.min()

0

In [12]:
ranarr.argmin()

1

In [11]:
ranarr[ranarr.argmin()]

3

## Shape

Shape is an attribute that arrays have (not a method):

In [35]:
arr.shape # Vector

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1) # now a vector in a 2 dimensional space

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

In [40]:
arr.dtype # type of data inside, everything has to be the same type

dtype('int32')

In [41]:
# same indexing as lists and strings

In [42]:
arr[8]

8

In [43]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [44]:
arr[:-3]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [45]:
arr[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [46]:
# because you know that every entry has the same type.

In [47]:
list_ = [1,2,3,4,5]
list[0:2] = 3     # you cannot assign multiple positions of a list

TypeError: 'type' object does not support item assignment

In [48]:
arr[0:5] = 100
arr # you can in an array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [208]:
arr = np.arange(0,11)

## slices

In [50]:
list_ = [0,1,2,3,4,5,6,7]
list_

[0, 1, 2, 3, 4, 5, 6, 7]

In [51]:
x = list_[0:2]
x  # if I save a part of a list, when you changed the saved part  it is not changing the original

[0, 1]

In [52]:
x[:] = 2, 3
x

[2, 3]

In [53]:
list_

[0, 1, 2, 3, 4, 5, 6, 7]

In [14]:
slice_of_arr = arr[0:6].copy()
slice_of_arr   # however with arrays, a saved part will affect original

array([0, 1, 2, 3, 4, 5])

In [55]:
slice_of_arr[:] = 99

In [56]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [57]:
arr # voila its changed

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### Data is not copied, it's a view of the original array! This avoids memory problems!

In [58]:
# You need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing matrices

In [15]:
arr_2d = np.array(([5,10,15,16],[20,25,30,31],[35,40,45,46],[50,55,60,61]))

arr_2d  # indexing arrays i the same as lists and strings, except you have to watch out for dimensions

array([[ 5, 10, 15, 16],
       [20, 25, 30, 31],
       [35, 40, 45, 46],
       [50, 55, 60, 61]])

In [16]:
arr_2d[1]

array([20, 25, 30, 31])

In [61]:
arr_2d[2:]

array([[35, 40, 45, 46],
       [50, 55, 60, 61]])

In [62]:
arr_2d[:-2]

array([[ 5, 10, 15, 16],
       [20, 25, 30, 31]])

In [18]:
arr_2d

array([[ 5, 10, 15, 16],
       [20, 25, 30, 31],
       [35, 40, 45, 46],
       [50, 55, 60, 61]])

In [17]:
arr_2d[1,2]

30

In [65]:
# or
arr_2d[1][2]

30

In [66]:
arr_2d

array([[ 5, 10, 15, 16],
       [20, 25, 30, 31],
       [35, 40, 45, 46],
       [50, 55, 60, 61]])

In [67]:
arr_2d[2:,:3]

array([[35, 40, 45],
       [50, 55, 60]])

In [68]:
arr_2d[::-1,::-1]

array([[61, 60, 55, 50],
       [46, 45, 40, 35],
       [31, 30, 25, 20],
       [16, 15, 10,  5]])

In [20]:
my_array = np.random.randint(0,100,(3,3,3))

In [21]:
my_array

array([[[94, 57,  0],
        [96,  9, 39],
        [ 3, 62, 42]],

       [[49, 64, 77],
        [20, 39, 28],
        [66, 23,  6]],

       [[29,  3, 39],
        [ 2, 38,  8],
        [ 6, 35, 57]]])

In [22]:
my_array[2,1,0]

2

## questions

In [72]:
my_array = np.random.randint(0,100,(5,5))

In [73]:
my_array

array([[40, 16, 93, 82, 65],
       [98, 82, 11, 97, 39],
       [83, 49, 88, 90, 78],
       [26, 35, 57, 53, 16],
       [39, 17, 29, 83, 50]])

In [74]:
# what will my_array[3,2] give?

In [75]:
my_array = np.random.randint(0,100,(3,3,3))

In [76]:
my_array

array([[[94, 63, 93],
        [18, 13, 76],
        [ 0, 68, 63]],

       [[96, 56,  4],
        [46, 26, 15],
        [65, 78, 69]],

       [[ 7, 77, 99],
        [74, 42, 55],
        [34, 10, 56]]])

In [77]:
# what will my_array[1,2,-1] give?

69

In [78]:
my_array[:2,1:,0]

array([[18,  0],
       [46, 65]])

In [79]:
# what will my_array[::-1,::-1][2,1,0] give?

18

## operations

In [80]:
my_array > 50 # like lists comparing numbers to a numpy will return true and falses

array([[[ True,  True,  True],
        [False, False,  True],
        [False,  True,  True]],

       [[ True,  True, False],
        [False, False, False],
        [ True,  True,  True]],

       [[False,  True,  True],
        [ True, False,  True],
        [False, False,  True]]])

In [81]:
my_array[my_array > 50] # returns all numbers more than 50

array([94, 63, 93, 76, 68, 63, 96, 56, 65, 78, 69, 77, 99, 74, 55, 56])

In [82]:
my_array[my_array > 80]

array([94, 93, 96, 99])

In [83]:
my_array + 4 # adds 4

array([[[ 98,  67,  97],
        [ 22,  17,  80],
        [  4,  72,  67]],

       [[100,  60,   8],
        [ 50,  30,  19],
        [ 69,  82,  73]],

       [[ 11,  81, 103],
        [ 78,  46,  59],
        [ 38,  14,  60]]])

In [84]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [86]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [87]:
arr / (arr+1)

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286],
       [0.875     , 0.88888889, 0.9       ]])

In [88]:
np.max(arr)

9

# Pandas

In [24]:
# Series data type

# NumPy array from a Series, 
#is that a Series can have axis labels, 
#meaning it can be indexed by a label, 
#instead of just a number location. 
#It also doesn't need to hold numeric data, 
#it can hold any arbitrary Python Object.


import numpy as np
import pandas as pd # built on numpy

In [90]:
# there are many ways to create a panda dataframe
# well go over a few

In [28]:
labels = ['a','b','c']

my_list = [10,20,30]

arr = np.array([10,20,30])

d = {'a':10,'b':20,'c':30}

In [34]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [26]:
# pd.Series(SHIFT TAB)
pd.Series()

# data, index, etc..

Series([], dtype: float64)

In [27]:
pd.Series(data=my_list,index=labels) # you can create with lists

NameError: name 'my_list' is not defined

In [95]:
pd.Series(my_list,labels)
#automatic

a    10
b    20
c    30
dtype: int64

In [96]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [97]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [98]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [99]:
pd.Series(data=labels) # doesnt have to be just numbers

0    a
1    b
2    c
dtype: object

In [35]:
ser_ = pd.Series(data=['a',2,'3','b'])
type(ser_[1])
type('01/06/22')

str

In [101]:
#like lists anything can go in

# Even functions (although unlikely that you will use this)
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [102]:
# pandas ca look up locations quickly, are similar to dictionarys

In [36]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])  
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [39]:
ser1['USA']

3

In [ ]:
ser1.USA

In [104]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [105]:
ser1['USA']

1

In [ ]:
ser1.index

In [106]:
ser1 + ser2  # adds them by index
# youre adding null to zero, doesnt make sense, so pc assumes nan

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [11]:
pd.DataFrame()

SyntaxError: invalid syntax (<ipython-input-11-9fd34bf1e8e6>, line 1)

In [42]:
df = pd.DataFrame(np.random.randint(0,100,(5,4)),
                  index='A B C D E'.split(),columns='W X Y Z'.split())

# hopefully this is implicit but df is a variable name
#  you can call a dataframe any name

In [43]:
df

W   X   Y   Z
A  19  22  82  13
B   0  53  70  49
C  65  34   3  64
D  12  18  82  87
E  37  85  75   1

In [210]:
pd.DataFrame(SHIFT TAB data, index, columns)

df = pd.DataFrame(randint(0,100,(5,4)),index='A B C D E'.split(),columns='W X Y Z'.split())

# hopefully this is implicit but df is a variable name
#  you can call a dataframe any namefrom numpy.random import randint  
#remember you can import specific things parts of packages

In [44]:
df

W   X   Y   Z
A  19  22  82  13
B   0  53  70  49
C  65  34   3  64
D  12  18  82  87
E  37  85  75   1

In [213]:
df['W'] # individual column

A    81
B    87
C    30
D    63
E    35
Name: W, dtype: int32

In [46]:
df[['W','Z']] #multiple

W   Z
A  19  13
B   0  49
C  65  64
D  12  87
E  37   1

In [215]:
df.loc['A']

A    81
B    87
C    30
D    63
E    35
Name: W, dtype: int32

In [216]:
type(df.W)

pandas.core.series.Series

In [55]:
df['new_'] = np.random.randint(0,100,5)
df

W   X   Y   Z  new_
A  19  22  82  13    85
B   0  53  70  49    65
C  65  34   3  64    46
D  12  18  82  87    15
E  37  85  75   1     7

In [57]:
df['new'] = df['W'] + df['Y'] 
# you can combine columns to create new columns
df

W   X   Y   Z  new_  new
A  19  22  82  13    85  101
B   0  53  70  49    65   70
C  65  34   3  64    46   68
D  12  18  82  87    15   94
E  37  85  75   1     7  112

In [63]:
df.drop('new',axis=1,inplace=True) # deletes column

In [64]:
df

W   X   Y   Z  new_
A  19  22  82  13    85
B   0  53  70  49    65
C  65  34   3  64    46
D  12  18  82  87    15
E  37  85  75   1     7

In [220]:
# axis=1 means columns, axis=0 which is default looks at rows

df.drop('E')

W   X   Y   Z  new
A  81  69  47  92  128
B  87  58  19  29  106
C  30  71  17  91   47
D  63  57  13  32   76

In [67]:
df

W   X   Y   Z  new_
A  19  22  82  13    85
B   0  53  70  49    65
C  65  34   3  64    46
D  12  18  82  87    15
E  37  85  75   1     7

In [68]:
df.drop('new_', axis=1).drop('E')

W   X   Y   Z
A  19  22  82  13
B   0  53  70  49
C  65  34   3  64
D  12  18  82  87

In [48]:
# df.W or df["W"]  works
df.loc['W'] #but this does not
#instead loc looks for rows first

KeyError: 'W'

In [49]:
df

W   X   Y   Z
A  19  22  82  13
B   0  53  70  49
C  65  34   3  64
D  12  18  82  87
E  37  85  75   1

In [50]:
df.loc['A','W'] # looks for row a then column w

19

In [51]:
df.loc['A']

W    19
X    22
Y    82
Z    13
Name: A, dtype: int32

In [119]:
df.loc['A'].W # multiple ways to do everything

62

In [120]:
df.loc['A']['W']

62

In [ ]:
df.iloc[0]

In [223]:
df.iloc[0,1] # looks at 0th row and 1st column

69

In [122]:
df.loc[['A','B'],['W','Y']] #looks for row a and b and columns w and y

W   Y
A  62   1
B  39  55

In [123]:
#df.TAB
df.columns # shows all columns

Index(['W', 'X', 'Y', 'Z', 'new'], dtype='object')

In [124]:
df.index # shows all rows

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [69]:
df>40  # is each point more than 40

W      X      Y      Z   new_
A  False  False   True  False   True
B  False   True   True   True   True
C   True  False  False   True   True
D  False  False   True   True  False
E  False   True   True  False  False

In [73]:
df['W']>30

A    False
B    False
C     True
D    False
E     True
Name: W, dtype: bool

In [75]:
df[df['W']>30] # all rows where the item in w is more than 40

W   X   Y   Z  new_
C  65  34   3  64    46
E  37  85  75   1     7

In [76]:
df[df['W']>30]['Y'] # looks at all rows where the item in w is more than 40 and then takes y column

C     3
E    75
Name: Y, dtype: int32

In [78]:
df

W   X   Y   Z  new_
A  19  22  82  13    85
B   0  53  70  49    65
C  65  34   3  64    46
D  12  18  82  87    15
E  37  85  75   1     7

In [79]:
df[(df['W']>40) & (df['Y'] > 33)]

Empty DataFrame
Columns: [W, X, Y, Z, new_]
Index: []

In [80]:
df.reset_index(drop=True) #will put default 
# you can change column labels and index labels

W   X   Y   Z  new_
0  19  22  82  13    85
1   0  53  70  49    65
2  65  34   3  64    46
3  12  18  82  87    15
4  37  85  75   1     7

In [82]:
newind = 'CA NY WY OR CO'.split() # split seperates wordsinto a list
df['States'] = newind
df

W   X   Y   Z  new_ States
A  19  22  82  13    85     CA
B   0  53  70  49    65     NY
C  65  34   3  64    46     WY
D  12  18  82  87    15     OR
E  37  85  75   1     7     CO

In [84]:
df.set_index('States', drop=False)

W   X   Y   Z  new_ States
States                             
CA      19  22  82  13    85     CA
NY       0  53  70  49    65     NY
WY      65  34   3  64    46     WY
OR      12  18  82  87    15     OR
CO      37  85  75   1     7     CO

In [133]:
df

W   X   Y   Z  new States
A  62  88   1  57   63     CA
B  39  95  55  52   94     NY
C  20  69  71  11   91     WY
D  81  92  88  43  169     OR
E  52  77  11  99   63     CO

In [134]:
df.set_index('States',inplace=True)
df

W   X   Y   Z  new
States                     
CA      62  88   1  57   63
NY      39  95  55  52   94
WY      20  69  71  11   91
OR      81  92  88  43  169
CO      52  77  11  99   63

## missing data

In [86]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [87]:
df.dropna() # drops any rows with null values, default is axis=0

C
0  1
1  2
2  3

In [138]:
df.dropna(axis=1) # if you change to axis=1 it looks at columns

C
0  1
1  2
2  3

In [88]:
df.dropna(thresh=2) # if you set the threshold only rows with 2 or more null values will be removed

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [140]:
df.fillna(value='FILL VALUE') # fills null values

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [141]:
df['A'].fillna(value=df['A'].mean()) #fills nulls of columns a with the mean of column a

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## combining dataframes

In [89]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])
print(df1)
print()
print(df2)
print()
print(df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11


In [144]:
pd.concat([df1,df2,df3]) # adds them to end since they all have same column names
# axis=0
df1.append(df2)
# another function that we will use later is append
# df.append(df2) and is the same as concat(axis=0, join='outer')

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [145]:
pd.concat([df1,df2,df3],axis=1) # they all have different row names so added diagonally

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [226]:
# if i reindexed so each df has rows labeled 0,1,2,3
df2.reset_index(drop=True, inplace=True)
df3.reset_index(drop=True, inplace=True)
pd.concat([df1,df2,df3],axis=1)

A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [97]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    
print(left)
print(right)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3
  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3


In [95]:
pd.merge(left,right,how='inner',on='key') # you can merge on a column (here we use key)

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K2  A2  B2  C2  D2
2  K3  A3  B3  C3  D3

In [99]:
right.rename(columns={'key':'key2'}, inplace=True) # renames column key to key0

In [100]:
pd.merge(left,right,how='inner',left_on='key', right_on ='key2') 
# merges on key in left df and on key0 in right

key   A   B key2   C   D
0  K0  A0  B0   K0  C0  D0
1  K1  A1  B1   K1  C1  D1
2  K2  A2  B2   K2  C2  D2
3  K3  A3  B3   K3  C3  D3

## groupby

In [101]:
# Create dataframe
df = pd.DataFrame({'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350], 'Sales2':[20,12,30,14,43,50]})
print(df)

  Company   Person  Sales  Sales2
0    GOOG      Sam    200      20
1    GOOG  Charlie    120      12
2    MSFT      Amy    340      30
3    MSFT  Vanessa    124      14
4      FB     Carl    243      43
5      FB    Sarah    350      50


In [102]:
by_comp = df.groupby("Company") # combines by company name

In [103]:
by_comp.mean() # mean of each company salary

Sales  Sales2
Company               
FB       296.5    46.5
GOOG     160.0    16.0
MSFT     232.0    22.0

In [172]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [104]:
by_comp.std() # standard deviation

Sales     Sales2
Company                       
FB        75.660426   4.949747
GOOG      56.568542   5.656854
MSFT     152.735065  11.313708

In [105]:
by_comp.min()

Person  Sales  Sales2
Company                        
FB          Carl    243      43
GOOG     Charlie    120      12
MSFT         Amy    124      14

In [106]:
by_comp.sale()

AttributeError: 'DataFrameGroupBy' object has no attribute 'value_counts'

In [107]:
by_comp.describe() # nice talbe of stats

Sales                                                         Sales2  \
        count   mean         std    min     25%    50%     75%    max  count   
Company                                                                        
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0    2.0   
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0    2.0   
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0    2.0   

                                                          
         mean        std   min    25%   50%    75%   max  
Company                                                   
FB       46.5   4.949747  43.0  44.75  46.5  48.25  50.0  
GOOG     16.0   5.656854  12.0  14.00  16.0  18.00  20.0  
MSFT     22.0  11.313708  14.0  18.00  22.0  26.00  30.0

In [177]:
by_comp.describe().transpose()['GOOG'] # transpose takes dataframe and rotates it

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

## Operations

In [108]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [111]:
df.tail() # takes top 2,    df.tail(2) would take bottom 2

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [183]:
df['col2'].unique() # all unique values

array([444, 555, 666], dtype=int64)

In [184]:
df['col2'].nunique() # number of unique values

3

In [185]:
df['col2'].value_counts() # how many of each unique value

444    2
555    1
666    1
Name: col2, dtype: int64

In [187]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]
newdf

col1  col2 col3
3     4   444  xyz

In [112]:
# you can use functions which will iterate on df's

def times2(x): # fuction that inputs number and outpust than number * 2
    return x*2

df['col1'].apply(times2)


In [114]:
times2(df)

col1  col2    col3
0     2   888  abcabc
1     4  1110  defdef
2     6  1332  ghighi
3     8   888  xyzxyz

In [117]:
df.drop('col3', axis=1)

col1  col2
0     1   444
1     2   555
2     3   666
3     4   444

In [118]:
del df['col1']

In [119]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [192]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [193]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [120]:
df.sort_values(by='col3') # inplace=False by default

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [121]:
df[df.isnull()]

col2 col3
0   NaN  NaN
1   NaN  NaN
2   NaN  NaN
3   NaN  NaN

In [196]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

## Reading

In [ ]:
# you can import files as long as they are in your directory.
# Look at the home tab, see where the files are saved. On the uni pc it should be the H: drive
# so move your excel or csv there
# you can import from other files/directories, but that requires getting the directory path

In [123]:
df = pd.read_csv('testing_spam.csv')  # you have to put full name including file type (i.e. .csv or .xlsx)
df

1.000000000000000000e+00  0.000000000000000000e+00  \
0                         1.0                       1.0   
1                         0.0                       0.0   
2                         0.0                       0.0   
3                         0.0                       0.0   
4                         0.0                       0.0   
5                         0.0                       0.0   
6                         0.0                       1.0   
7                         0.0                       0.0   
8                         0.0                       0.0   
9                         0.0                       0.0   
10                        0.0                       0.0   
11                        0.0                       0.0   
12                        0.0                       1.0   
13                        0.0                       0.0   
14                        0.0                       1.0   
15                        1.0                       1.0   
16                        0.0                       0.0   
17                        1.0                       0.0   
18                        1.0                       0.0   
19                        0.0                       0.0   
20                        1.0                       0.0   
21                        0.0                       0.0   
22                        0.0                       1.0   
23                        1.0                       1.0   
24                        1.0                       0.0   
25                        0.0                       1.0   
26                        0.0                       0.0   
27                        1.0                       0.0   
28                        0.0                       0.0   
29                        0.0                       0.0   
..                        ...                       ...   
469                       0.0                       1.0   
470                       0.0                       0.0   
471                       0.0                       0.0   
472                       1.0                       1.0   
473                       1.0                       1.0   
474                       0.0                       0.0   
475                       0.0                       0.0   
476                       0.0                       0.0   
477                       0.0                       0.0   
478                       1.0                       0.0   
479                       0.0                       0.0   
480                       1.0                       0.0   
481                       1.0                       1.0   
482                       0.0                       0.0   
483                       1.0                       0.0   
484                       0.0                       1.0   
485                       1.0                       0.0   
486                       1.0                       0.0   
487                       1.0                       1.0   
488                       0.0                       0.0   
489                       1.0                       0.0   
490                       0.0                       0.0   
491                       0.0                       0.0   
492                       0.0                       0.0   
493                       0.0                       0.0   
494                       0.0                       0.0   
495                       0.0                       0.0   
496                       0.0                       0.0   
497                       0.0                       0.0   
498                       0.0                       0.0   

     0.000000000000000000e+00.1  1.000000000000000000e+00.1  \
0                           0.0                         1.0   
1                           0.0                         0.0   
2                           0.0                         0.0   
3                           0.0                         0.0   
4                           0.0

In [122]:
df = pd.read_excel('testing_spam.xlxs') # insert name here
df # I dont have one so there is an error

FileNotFoundError: [Errno 2] No such file or directory: 'testing_spam.xlxs'

In [ ]:
# you can save adata ot an excel or csv using .to_excel() or .to_csv()
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [ ]:
df = pd.read_

In [201]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html') # you can read some websites with .read_html

#we will cover more advanced scraping with beautifulsoup in a different class 

In [203]:
df[0]

Bank Name                City  \
0                                        Resolute Bank              Maumee   
1                                Louisa Community Bank              Louisa   
2                                 The Enloe State Bank              Cooper   
3                  Washington Federal Bank for Savings             Chicago   
4      The Farmers and Merchants State Bank of Argonia             Argonia   
5                                  Fayette County Bank          Saint Elmo   
6    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
7                                       First NBC Bank         New Orleans   
8                                        Proficio Bank  Cottonwood Heights   
9                        Seaway Bank and Trust Company             Chicago   
10                              Harvest Community Bank          Pennsville   
11                                         Allied Bank            Mulberry   
12                        The Woodbury Banking Company            Woodbury   
13                              First CornerStone Bank     King of Prussia   
14                                  Trust Company Bank             Memphis   
15                          North Milwaukee State Bank           Milwaukee   
16                              Hometown National Bank            Longview   
17                                 The Bank of Georgia      Peachtree City   
18                                        Premier Bank              Denver   
19                                      Edgebrook Bank             Chicago   
20                              Doral Bank  En Español            San Juan   
21                   Capitol City Bank & Trust Company             Atlanta   
22                             Highland Community Bank             Chicago   
23                    First National Bank of Crestview           Crestview   
24                                  Northern Star Bank             Mankato   
25              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
26               The National Republic Bank of Chicago             Chicago   
27                                      NBRS Financial          Rising Sun   
28                               GreenChoice Bank, fsb             Chicago   
29                            Eastside Commercial Bank             Conyers   
..                                                 ...                 ...   
528                                  ANB Financial, NA         Bentonville   
529                                          Hume Bank                Hume   
530                             Douglass National Bank         Kansas City   
531                                  Miami Valley Bank            Lakeview   
532                                            NetBank          Alpharetta   
533                          Metropolitan Savings Bank          Pittsburgh   
534                                    Bank of Ephraim             Ephraim   
535                                      Reliance Bank        White Plains   
536              Guaranty National Bank of Tallahassee         Tallahassee   
537                                Dollar Savings Bank              Newark   
538                               Pulaski Savings Bank        Philadelphia   
539              First National Bank of Blanchardville      Blanchardville   
540                              Southern Pacific Bank            Torrance   
541                        Farmers Bank of Cheneyville         Cheneyville   
542                                      Bank of Alamo               Alamo   
543             AmTrade International Bank  En Español             Atlanta   
544                     Universal Federal Savings Bank             Chicago   
545                       Connecticut Bank of Commerce            Stamford   
546                                   New Century Bank     Shelby Township   
547                              Net 1st National Bank          Boc

In [ ]:
# some questions
https://www.machinelearningplus.com/python/101-numpy-exercises-python/
https://www.machinelearningplus.com/python/101-pandas-exercises-python/