## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

### Task #1

Given price = 300 , use python to figure out the square root of the price.

In [3]:
price = 300

In [4]:
price**0.5

17.320508075688775

In [6]:
import math
math.sqrt(price)

17.320508075688775

### Task #2

Given the string:

    stock_index = "SP500"
   
Grab '500' from the string using indexing.

In [1]:
stock_index = "SP500"

In [2]:
stock_index[2:]

'500'

### Task #3

** Given the variables:**

    stock_index = "SP500"
    price = 300

** Use .format() to print the following string: **

    The SP500 is at 300 today.

In [7]:
stock_index = "SP500"
price = 300

In [9]:
print("The {} is at {} today.".format(stock_index,price))

The SP500 is at 300 today.


### Task #4

** Given the variable of a nested dictionary with nested lists: **

    stock_info = {'sp500':{'today':300,'yesterday': 250}, 'info':['Time',[24,7,365]]}
    
** Use indexing and key calls to grab the following items:**

* Yesterday's SP500 price (250)
* The number 365 nested inside a list nested inside the 'info' key.

In [10]:
stock_info = {'sp500':{'today':300,'yesterday': 250}, 'info':['Time',[24,7,365]]}

In [12]:
stock_info['sp500']['yesterday']

250

In [15]:
stock_info['info'][1][2]

365

### Task #5

** Given strings with this form where the last source value is always separated by two dashes -- **

    "PRICE:345.324:SOURCE--QUANDL"
    
**Create a function called source_finder() that returns the source. For example, the above string passed into the function would return "QUANDL"**

In [16]:
def source_finder(s):
    return s.split('--')[-1]

In [18]:
source_finder("PRICE:345.324:SOURCE--QUANDL")

'QUANDL'

### Task #5

** Create a function called price_finder that returns True if the word 'price' is in a string. Your function should work even if 'Price' is capitalized or next to punctuation ('price!')  **

In [19]:
def price_finder(s):
    return 'price' in s.lower()

In [20]:
price_finder("What is the price?")

True

In [22]:
price_finder("DUDE, WHAT IS PRICE!!!")

True

In [23]:
price_finder("The price is 300")

True

### Task #6

** Create a function called count_price() that counts the number of times the word "price" occurs in a string. Account for capitalization and if the word price is next to punctuation. **

In [46]:
def count_price(s):
    count = 0
    for word in s.lower().split():
        # Need to use in, can't use == or will get error with punctuation
        if 'price' in word:
            count += 1
            
    # Note the indentation!
    return count

In [43]:
# Simpler Alternative
def count_price(s):
    return s.lower().count('price')

In [44]:
s = 'Wow that is a nice price, very nice Price! I said price 3 times.'

In [47]:
count_price(s)

3

### Task #7

**Create a function called avg_price that takes in a list of stock price numbers and calculates the average (Sum of the numbers divided by the number of elements in the list). It should return a float. **

In [27]:
def avg_price(stocks):
    return sum(stocks)/len(stocks) # Python 2 users should multiply numerator by 1.0

In [30]:
avg_price([3,4,5])

4.0

# NumPy Exercises - Solutions

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

** IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output! **

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
# CODE HERE

In [2]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

In [ ]:
# CODE HERE

In [3]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [ ]:
# CODE HERE

In [4]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

In [ ]:
# CODE HERE

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
# CODE HERE

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# CODE HERE

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
# CODE HERE

In [8]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
# CODE HERE

In [15]:
np.random.rand(1)

array([ 0.42829726])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
# CODE HERE

In [33]:
np.random.randn(25)

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

In [35]:
np.arange(1,101).reshape(10,10) / 100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [36]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
# CODE HERE

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [40]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [41]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
# CODE HERE

In [50]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [ ]:
# CODE HERE

In [51]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [ ]:
# CODE HERE

In [53]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

## difficult questions

#### 1) Mina has been told by John that to learn welsh you have to speak backwards. Can you build a function that translates a sentance into welsh.

#### 2) Bram tells her that she is being stupid that the order of the words should not change.

#### 3) Quincey being a good guy tells her that they're both wrong. That she simply has to scale the language by one to the right a->b, b->c, z->a
#### hint( mess around with ord() and chr)

#### 4) Quincey also tells her that all languages can be translated this way. Create a function where you input string and how many characters to slide

## answers

In [ ]:
# 1
def john_welsh(sentence):
    return sentence[::-1]

In [10]:
# 2
def stoker(sentence):
    input_ = sentence.split()
    for i in range(len(input_)):
        input_[i] = input_[i][::-1]
    return input_

In [5]:
# 3
def lucy(sentence):
    input_ = sentence.lower().split()   # other ways to do multiple functions
    for i in range(len(input_)):
        output=""
        for a in range(len(input_[i])):
            temp_letter = ord(input_[i][a]) + 1
            if temp_letter == 123: 
                temp_letter = temp_letter - 26
            output += chr(temp_letter)
        input_[i] = output
    output = " ".join(input_)
    return output

In [6]:
# 4
def dracula(sentence, shifts):
    input_ = sentence.lower().split()   # other ways to do multiple functions
    for i in range(len(input_)):
        output=""
        for a in range(len(input_[i])):
            temp_letter = ord(input_[i][a]) + shifts
            if temp_letter > 122: 
                temp_letter = temp_letter - 26
            output += chr(temp_letter)
        input_[i] = output
    output = " ".join(input_)
    return output

In [8]:
lucy("my name is alex")

'nz obnf jt bmfy'